### ISSUE TITLE
which vscode theme is shown on the website doc? 🙂

### ISSUE THREAD

**Issue by RichieRunner** [cerebral/overmind-website#13]
which vscode theme is shown on the website doc? 🙂
![image](https://user-images.githubusercontent.com/20289967/82473471-748a5100-9a7e-11ea-800f-5795f1c398dd.png)
thanks.

**Comment by christianalfoni** [comment]
Sorry for extremely late answer! No idea 😄 It is just GitBook, dunno what they use
