### ISSUE TITLE
Questions about TypeScript page 

### ISSUE THREAD

**Issue by glenkitchen** [cerebral/overmind-website#19]
Personally, I think the [configuration section](https://overmindjs.org/core/typescript#configuration) on the TypeScript page, is a little confusing and assumes knowledge of a TypeScript feature that is not widely understood. (By me, up to now, anyway!)   

1.  Under Explicit Typing section the note says the 'The Overmind documentation is written for implicit typing'.
Is implicit typing the Declare module approach?     

2. At first, I did not understand what typeof was doing here:      
```
// Due to circular typing we have to define an
// explicit typing of state, actions and effects since
// TS 3.9
export interface Config extends IConfig<{
  state: typeof config.state,
  actions: typeof config.actions,
  effects: typeof config.effects
}> {}
```
I only understood the code (I hope!) after reading this [article](https://mariusschulz.com/blog/type-queries-and-typeof-in-typescript).

I think the documentation may benefit from the following blurb, or similar. 
```
// Note: The typeof keyword is being used here by TypeScript to type query
// the configuration.
// (It is NOT being used by JavaScript to return the type of the operand 
// as a string.)
// See https://mariusschulz.com/blog/type-queries-and-typeof-in-typescript for
// an explanation of the differences between typeof in TypeScript and JavaScript.
```
I am happy to submit a pull request for the above, but I thought I would get some feedback first, and ascertain whether I have properly understood the concepts.

**Comment by christianalfoni** [comment]
Hi and very sorry for late reply, I was not aware of these issues! 😞 

I am currently planning to do a bigger change here, please let me know what you think: https://github.com/cerebral/overmind/issues/481
