### ISSUE TITLE
Typo in TypeScript for getter. Missing colon `:`

### ISSUE THREAD

**Issue by deadcoder0904** [cerebral/overmind-website#5]
I found some typos on https://overmindjs.org/core/typescript

For exammple, the following code:

```ts
import { derived } from 'overmind'

type State = {
  foo: string
  shoutedFoo string
}

export const state: State = {
  foo: 'bar',
  shoutedFoo: derived<State, string>(state => state.foo + '!!!')
}
```

I think `shoutedFoo string` should be `shoutedFoo: string`. There is a missing colon. There are bunch of other code blocks where there is a missing colon :)

**Comment by christianalfoni** [comment]
So sorry, I did not see these issues until now... crazy, but yeah, this is fixed 😄
